__title__ = "river"
__description__ = "A Python-to-S3 interface with added convenience."
__url__ = "https://github.com/neighborhoods/river"
__version__ = "0.1"
__author__ = "George Wood (@Geoiv)"
__author_email__ = "george.wood@55places.com"
