__title__ = "river"
__description__ = "A Python-to-S3 interface with added convenience features."
__url__ = "https://github.com/neighborhoods/river"
__version__ = "1.3.0"
__author__ = "George Wood (@Geoiv)"
__author_email__ = "wood.georgeiv@gmail.com"
